name: autodock
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - biopython
   - matplotlib
   - numpy
   - autodock-vina
#  - autodocktools-prepare ### this does not install
   - python
